# SPDX-License-Identifier: GPL-2.0
dvb-usb-v2-objs := neumo-dvb-usb-core.o neumo-dvb-usb-urb.o usb_urb.o
dvb-usb-v2-objs += neumo-dvb-usb-core-dvbapi.o neumo-dvb-usb-urb-dvbapi.o
obj-$(CONFIG_DVB_USB_V2) += dvb-usb-v2.o

dvb-usb-rtl28xxu-objs := rtl28xxu.o
obj-$(CONFIG_DVB_USB_RTL28XXU) += dvb-usb-rtl28xxu.o

ccflags-y += -I$(M)/frontends
ccflags-y += -I$(M)/frontends
ccflags-y += -I$(M)/tuners
ccflags-y += -I$(M)/dvb-core
