# SPDX-License-Identifier: GPL-2.0
neumo-dvb-usb-objs += dvb-usb-firmware.o neumo-dvb-usb-init.o neumo-dvb-usb-urb.o  dvb-usb-i2c.o
neumo-dvb-usb-objs += dvb-usb-dvb.o neumo-dvb-usb-remote.o usb-urb.o
obj-$(CONFIG_DVB_USB) += neumo-dvb-usb.o

neumo-dvb-usb-tbsqbox-objs = tbs-qbox.o
obj-$(CONFIG_DVB_USB_TBSQBOX) += neumo-dvb-usb-tbsqbox.o

neumo-dvb-usb-tbsqbox2-objs = tbs-qbox2.o
obj-$(CONFIG_DVB_USB_TBSQBOX2) += neumo-dvb-usb-tbsqbox2.o

neumo-dvb-usb-tbsqbox22-objs = tbs-qbox22.o
obj-$(CONFIG_DVB_USB_TBSQBOX22) += neumo-dvb-usb-tbsqbox22.o

neumo-dvb-usb-tbs5922se-objs = tbs5922se.o
obj-$(CONFIG_DVB_USB_TBS5922SE) += neumo-dvb-usb-tbs5922se.o

neumo-dvb-usb-tbsqboxs2-objs = tbs-qboxs2.o
obj-$(CONFIG_DVB_USB_TBSQBOXS2) += neumo-dvb-usb-tbsqboxs2.o

neumo-dvb-usb-tbsqbox2ci-objs = tbs-qbox2ci.o
obj-$(CONFIG_DVB_USB_TBSQBOX2CI) += neumo-dvb-usb-tbsqbox2ci.o

neumo-dvb-usb-tbs5925-objs = tbs5925.o
obj-$(CONFIG_DVB_USB_TBS5925) += neumo-dvb-usb-tbs5925.o

neumo-dvb-usb-tbs5880-objs = tbs5880.o
obj-$(CONFIG_DVB_USB_TBS5880) += neumo-dvb-usb-tbs5880.o

neumo-dvb-usb-tbs5220-objs = tbs5220.o
obj-$(CONFIG_DVB_USB_TBS5220) += neumo-dvb-usb-tbs5220.o

neumo-dvb-usb-tbs5230-objs = tbs5230.o
obj-$(CONFIG_DVB_USB_TBS5230) += neumo-dvb-usb-tbs5230.o

neumo-dvb-usb-tbs5881-objs = tbs5881.o
obj-$(CONFIG_DVB_USB_TBS5881) += neumo-dvb-usb-tbs5881.o

neumo-dvb-usb-tbs5520-objs := tbs5520.o
obj-$(CONFIG_DVB_USB_TBS5520) += neumo-dvb-usb-tbs5520.o

neumo-dvb-usb-tbs5520se-objs = tbs5520se.o
obj-$(CONFIG_DVB_USB_TBS5520se) += neumo-dvb-usb-tbs5520se.o

neumo-dvb-usb-tbs5530-objs = tbs5530.o
obj-$(CONFIG_DVB_USB_TBS5530) += neumo-dvb-usb-tbs5530.o

neumo-dvb-usb-tbs5580-objs = tbs5580.o
obj-$(CONFIG_DVB_USB_TBS5580) += neumo-dvb-usb-tbs5580.o

neumo-dvb-usb-tbs5927-objs = tbs5927.o
obj-$(CONFIG_DVB_USB_TBS5927) += neumo-dvb-usb-tbs5927.o

neumo-dvb-usb-tbs5301-objs = tbs5301.o
obj-$(CONFIG_DVB_USB_TBS5301) += neumo-dvb-usb-tbs5301.o

neumo-dvb-usb-tbs5930-objs = tbs5930.o
obj-$(CONFIG_DVB_USB_TBS5930) += neumo-dvb-usb-tbs5930.o

neumo-dvb-usb-tbs5931-objs = tbs5931.o
obj-$(CONFIG_DVB_USB_TBS5931) += neumo-dvb-usb-tbs5931.o

neumo-dvb-usb-tbs5590-objs = tbs5590.o
obj-$(CONFIG_DVB_USB_TBS5590) += neumo-dvb-usb-tbs5590.o

ccflags-y += -I$(M)/frontends/
ccflags-y += -I$(M)/tuners
