# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel DVB device drivers.
#

dvb-net-$(CONFIG_DVB_NET) := neumo-dvb-net.o
dvb-vb2-$(CONFIG_DVB_MMAP) := dvb_vb2.o

compat-y := neumo-dvb-demux-dvbapi.o    \
         neumo-dvb-ca-en50221-dvbapi.o  \
         neumo-frontend-dvbapi.o        \
         neumo-dmxdev-dvbapi.o

dvb-core-objs := neumo-dvbdev.o     \
                 neumo-dmxdev.o     \
                 neumo-dvb-demux.o  \
		 neumo-dvb-ca-en50221.o \
                 neumo-dvb-frontend.o	\
		 $(dvb-net-y) \
                 dvb_ringbuffer.o \
                 $(dvb-vb2-y) \
                 dvb_math.o \
                 neumo-dmxdev-sysfs.o \
                 neumo-scan.o \
                 $(compat-y)

obj-$(CONFIG_DVB_CORE) += dvb-core.o

EXTRA_CFLAGS += -DCONFIG_DVB_DYNAMIC_MINORS -DCONFIG_DVB_NET
